# Generated by Django 5.1.5 on 2025-01-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, default='808080', max_length=6),
        ),
    ]
