# Generated by Django 5.1.5 on 2025-01-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(default='#808080', max_length=7),
        ),
    ]
